sudo: required
services: 
  - docker

before_install:
  - docker build -t blazejszczerba/reimagined-lamp -f Dockerfile.dev .

script: 
  - docker run blazejszczerba/reimagined-lamp npm run test -- --coverage